### ISSUE TITLE
Checklist for 1.0 release

### ISSUE THREAD

**Issue by jeffesquivels** [nimiq/core-rs#40]
This is the checklist of pending items/bugs/tasks that need to be addressed in order to release a 1.0 version:

- [x] Looking into networking layer improvements in `albatross` and backporting anything that makes sense
- [x] Make sure TLS termination works properly with our current mainnet infrastructure setup
- [x] Backport the updated GitLab CI config from `albatross`
- [x] Fix bug where incomplete AccountsProof are sent
- [x] Code cleanup (warnings during compilation, etc.)
- [ ] Support https for the metrics server
- [ ] Make sure the name of metrics in Rust match those in JavaScript

**Comment by jgraef** [comment]
- [x] Update README
 - [x] Update comments in example config file

**Comment by jgraef** [comment]
I don't think we can use PEM files for the TLS certificates as native_tls haven't finished that feature yet[1]

[1] https://github.com/sfackler/rust-native-tls/issues/27

**Comment by jeffesquivels** [comment]
> I don't think we can use PEM files for the TLS certificates as native_tls haven't finished that feature yet[1]
> 
> [1] [sfackler/rust-native-tls#27](https://github.com/sfackler/rust-native-tls/issues/27)

I moved this to #41 so that it can be tracked and fixed post-release.
