### ISSUE TITLE
Backport checklist from Albatross

### ISSUE THREAD

**Issue by jeffesquivels** [nimiq/core-rs#42]
This issue is a meta issue with the information of all the features that should/could be backported from Albatross after the stable release:

- [ ] Client API support
- [ ] Build genesis block data from config file
- [ ] Move paths of dependencies to root crate
